version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 1
  reviewers:
  - kylemh
  assignees:
  - kylemh
  ignore:
  - dependency-name: babel-plugin-tester
    versions:
    - 9.2.0
  - dependency-name: "@babel/core"
    versions:
    - 7.10.3
  - dependency-name: jest
    versions:
    - 26.0.1
